### ISSUE TITLE
Remove usage of deprecated dplyr function `funs`

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#15]
Function `print_tbl` uses the dplyr function `funs`. The help for that function makes it clear that it is deprecated. The help page says:

> funs() is deprecated; please use list() instead. We deprecated this function because it provided a unique way of specifying anonymous functions, rather than adopting the conventions used by purrr and other packages in the tidyverse.

**Comment by dholstius** [comment]
Closed by 188b42c; `print_tbl()` is now defunct.
