### ISSUE TITLE
Function `humanize` does not appear to exist

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#17]
R CMD CHECK has this NOTE
```
  print_tbl: no visible global function definition for ‘humanize’
```

My normal way to address these NOTEs is to find where the function is located and add an `#' @importFrom <packages> <function name>` to the top of the file. However, in this case, it appears that `humanize` is not really defined anywhere. 

When I type `??humanize` nothing comes up. The closest is `str_humanize` in `strtools`. Is that what's meant here?

**Comment by dholstius** [comment]
Closed by 188b42c; `print_tbl()` is now defunct.
