### ISSUE TITLE
function `replace_which` appears to not exist

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#18]
R CMD CHECK has this NOTE
```
  print_tbl: no visible global function definition for ‘replace_which’
```
My normal way to address these NOTEs is to find where the function is located and add an #' @importFrom <packages> <function name> to the top of the file. However, in this case, it appears that ‘replace_which’ is not defined anywhere.

When I type `??replace_which` nothing comes up.

**Comment by dholstius** [comment]
Closed by 188b42c; `print_tbl()` is now defunct.
