### ISSUE TITLE
Package `tidync` is required but not installed on server

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#27]
R CMD CHECK yields this warning:
> '::' or ':::' imports not declared from:
    ... ‘tidync’

The issue is [this](https://github.com/BAAQMD/tbltools/blob/master/R/read_ncdf.R#L22) line from `read_ncdf`. 
```
  ncdf_object <-
    tidync::tidync(path)
```
The normal solution to this warning is to add the roxygen note `#' @importFrom tidync tidync` to the top of the function and make sure that `tidync` is listed in the `Imports` section of the DESCRIPTION file. 

Doing this, however, results in an error, because the `tidync` package is not available on the server. Presumably I could get around this error by installing it locally. But I think that if we want anyone who uses the server to be able to use all the functionality of the `tbltools` package, then we should have the `tidync` package also installed by default on the server for everyone.

How does this sound to you @dholstius ?

**Comment by dholstius** [comment]
Yep. Folks will want to work with NetCDF files on the server!

I've installed `tidync` in the site library, for everyone. If that resolves this for you, please go ahead and close!
