### ISSUE TITLE
`Error: pandoc document conversion failed with error 137`

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/tbltools#36]
When running the R Pipeline it crashes in `600-onroad.R`. The error appears to be this code:
```
BY2015_onroad_mobile_emission_data %>%
  filter(
    ems_qty > 0) %>%
  with_hierarchy(
    BY2015_category_hierarchy,
    warn_missing = TRUE,
    verbose = TRUE) %>%
  select(
    -cat_h0) %>%
  # left_join(
  #   BY2015_category_staff_lookup,
  #   by = "cat_id") %>%
  pivot_table(
    rows = c("cat_h1", "cat_h2"),
    inclusions = list(
      year = as.list(str_c("CY", seq(1990, 2040, by = 5))), # every 5 years
      pol_abbr = list("PM"))) %>%
  write_pivot_table(
    BY2015_output_path(
      "Tables", "Pivot", "Summary", "Module",
      "BY2015-pivot-summary-600_onroad.html"),
    selfcontained = TRUE,
    verbose = TRUE)
```

If I run everything before the last `%>%` I get an object that is 54MB. The code crashes in the call to `write_pivot_table` and it gives this cryptic message: 
```
Killed
Error: pandoc document conversion failed with error 137
```

I assume that the object is just too large for that function to work with. @dholstius recommended I post the issue here along with a link to this issue: https://github.com/BAAQMD/tbltools/issues/2

**Comment by arilamstein** [comment]
Quick update: I believe that one of the previous suggestions was to round the numbers. The idea there was that reducing the number of digits would reduce the size of the object which in turn might lead to no longer crashing.

However, a call to `object.size` on each column reveals that each of the 12 columns seems to be identical size:
```
> data_to_pivot = BY2015_onroad_mobile_emission_data %>%
  filter(
    ems_qty > 0) %>%
  with_hierarchy(
    BY2015_category_hierarchy,
    warn_missing = TRUE,
    verbose = TRUE) %>%
  select(
    -cat_h0)

> head(data_to_pivot) 
# A tibble: 6 x 12
  year  cat_id pol_abbr cnty_abbr ems_qty ems_unit cat_h1 cat_h2 cat_h3 cat_h4
  <CY>   <dbl> <chr>    <chr>       <dbl> <chr>    <chr>  <chr>  <chr>  <chr> 
1 CY19…   1371 CO       ALA         287.  ton/yr   COMBU… ON RO… Heavy… Exhau…
2 CY19…   1371 CO2      ALA       26312.  ton/yr   COMBU… ON RO… Heavy… Exhau…
3 CY19…   1371 NOx      ALA         311.  ton/yr   COMBU… ON RO… Heavy… Exhau…
4 CY19…   1371 PM10     ALA          32.1 ton/yr   COMBU… ON RO… Heavy… Exhau…
5 CY19…   1371 PM2.5    ALA          29.5 ton/yr   COMBU… ON RO… Heavy… Exhau…
6 CY19…   1371 ROG      ALA         165.  ton/yr   COMBU… ON RO… Heavy… Exhau…
# … with 2 more variables: cat_h5 <chr>, cat_h6 <chr>
> format(object.size(data_to_pivot), units="auto")
[1] "51.5 Mb"
> # size by column
> for (col in colnames(data_to_pivot))
+ {
+   print(paste0(col, ": ", format(object.size(data_to_pivot[,col]), units="auto")))
+ }
[1] "year: 4.3 Mb"
[1] "cat_id: 4.3 Mb"
[1] "pol_abbr: 4.3 Mb"
[1] "cnty_abbr: 4.3 Mb"
[1] "ems_qty: 4.3 Mb"
[1] "ems_unit: 4.3 Mb"
[1] "cat_h1: 4.3 Mb"
[1] "cat_h2: 4.3 Mb"
[1] "cat_h3: 4.3 Mb"
[1] "cat_h4: 4.3 Mb"
[1] "cat_h5: 4.3 Mb"
[1] "cat_h6: 4.3 Mb"
```

This result is worth reporting. But it is also worth reporting that I don't see how it could possibly be true. For example, on average, each entry in `cnty_abbr` is just a fraction of the size of each entry in `cat_h1`:
```
> mean(nchar(data_to_pivot$cnty_abbr))
[1] 2.667762
> mean(nchar(data_to_pivot$cat_h1))
[1] 27
```

Based on this, I would expect the size of the `cat_h1` column to be about 13x as big as the `cnty_abbr` column. Yet they are equal.

While I suspect that this result is incorrect, I still think it's worth reporting here as others will likely run into similar issues as they investigate the issue.

cc @ydu0316 who I was speaking with earlier today about this bug.

**Comment by arilamstein** [comment]
I think I found a way to remove at least some of the data of the object while not removing any useful data. First: note that the original code removes `cat_h0`:
```
BY2015_onroad_mobile_emission_data %>%
  filter(
    ems_qty > 0) %>%
  with_hierarchy(
    BY2015_category_hierarchy,
    warn_missing = TRUE,
    verbose = TRUE) %>%
  select(
    -cat_h0)
```

Presumably `cat_h0` is removed because its value is `"Motor Vehicles"` for each row. 

It turns out that `cat_h1` and `cat_h2` also only have one value for each row. So presumably they also not need to be included:
```
> unique(data_to_pivot$cat_h1)
[1] "COMBUSTION - MOBILE SOURCES"
> unique(data_to_pivot$cat_h2)
[1] "ON ROAD MOTOR VEHICLES"
```

If we believe the `object.size` data above (which I don't), then this would remove 8.6Mb (~17%) of data from the final object we need to render with essentially no loss of information. Ideally we would preserve this data as metadata somewhere. But since it is the same for all data in the table, and we are trying to reduce size here, this seems like a good tradeoff. 

I will look into implementing this next and will report the results back here.

**Comment by arilamstein** [comment]
Upate: this works. The app no longer crashes with this error message and I can view the graph in HTML. I will rerun now.

**Comment by arilamstein** [comment]
The new release is titled `BY2015/Release/Release-20210630`. 

The file which was failing to be created before was `Output/Tables/Pivot/Summary/Module/BY2015-pivot-summary-600_onroad.html`

**Comment by abhinavguha** [comment]
Thanks @arilamstein . @arilamstein and @songbai-BAAQMD - We will not have this Issue (with at least the on-road mobile source module) anymore in future releases too so we are good to close this one. Please note that this Issue may recur in the Point Source module which will have a voluminous set of raw data unless we build safeguards in the processing code itself. I do not think we will be able to get rid of columns like cat_h0, cat_h1 etc. from that data set so may be we will need an alternate solution.
